# Generated by Django 4.2.29 on 2026-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_orders_cancellation_reason_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancellation Requested', 'Cancellation Requested'), ('Return Requested', 'Return Requested')], max_length=50, null=True),
        ),
    ]
