# Generated by Django 4.2.29 on 2026-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_orders_return_reason_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Home', 'Home'), ('Beauty', 'Beauty'), ('Books', 'Books'), ('Sports', 'Sports'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
