# Generated by Django 4.2.29 on 2026-04-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
