# Generated by Django 4.2.29 on 2026-04-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0021_order_return_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('cod', 'Cash on Delivery')], default='card', max_length=20),
        ),
    ]
